const makeCards = (items) =>
  items.map(([tag, front, back]) => ({
    tag,
    front,
    back,
  }));

const TOPICS = [
  {
    slug: "vida-diaria",
    number: "01",
    title: "Vida diaria",
    subtitle: "去基础后的日常表达，偏 B1+ 节奏与状态",
    accent: "#cb6c53",
    points: [
      "去掉最基础动作词，转向更真实的日常组织表达。",
      "重点是时间管理、状态、任务与节奏。",
      "很多词适合口语自述和写作。",
      "优先熟悉固定搭配。",
    ],
    why: "你前面基础已经够了，这一组更适合补真实生活里更像 B1+ 的说法。",
    core: [
      "不是只会说忙或累，而是能更具体地描述节奏和状态。",
      "优先记短语块，而不是孤立单词。",
      "很多表达都能直接迁移到写作。",
    ],
    focus: [
      "先记时间与任务管理。",
      "再记心理和身体状态。",
      "尽量用自己的日程套例句。",
    ],
    cards: makeCards([
      ["Verbo", "aplazar", "推迟。例：Tuve que aplazar la reunión porque me surgió un imprevisto."],
      ["Verbo", "rendir", "发挥效率。例：Si duermo poco, al día siguiente no rindo nada."],
      ["Verbo", "despejarse", "清醒；放松脑子。例：Salgo a caminar diez minutos para despejarme."],
      ["Expresión", "hacerse cargo de", "负责；处理。例：Esta semana me toca hacerme cargo de varias tareas urgentes."],
      ["Expresión", "tener margen", "有余地。例：Salimos antes para tener margen por si había tráfico."],
      ["Expresión", "ir justo de tiempo", "时间很紧。例：No puedo pararme ahora; voy justo de tiempo."],
      ["Expresión", "dejar algo a medias", "把事做到一半。例：No me gusta dejar las cosas a medias."],
      ["Expresión", "ponerse con algo", "开始做某事。例：Después de comer me pondré con el informe."],
      ["Expresión", "cumplir con", "履行；完成。例：Intento cumplir con todo, aunque a veces no llego."],
      ["Verbo", "sobrellevar", "熬过；应付。例：Con humor se sobrelleva mejor una semana complicada."],
      ["Verbo", "conciliar", "兼顾。例：No siempre es fácil conciliar el trabajo y la vida personal."],
      ["Sustantivo", "la carga diaria", "日常负担。例：Su carga diaria aumentó mucho este mes."],
      ["Sustantivo", "el imprevisto", "突发情况。例：Siempre dejo un hueco libre por si surge algún imprevisto."],
      ["Sustantivo", "el ritmo acelerado", "快节奏。例：El ritmo acelerado de la ciudad me agota bastante."],
      ["Sustantivo", "la falta de sueño", "睡眠不足。例：La falta de sueño me afecta más de lo que pensaba."],
      ["Verbo", "distraerse", "分心。例：Me distraigo enseguida si tengo el móvil al lado."],
      ["Expresión", "mantener la concentración", "保持专注。例：Me cuesta mantener la concentración por la tarde."],
      ["Verbo", "posponer", "延后。例：Vamos a posponer ese tema hasta mañana."],
      ["Expresión", "reorganizar la agenda", "重新安排日程。例：Tuve que reorganizar la agenda por un cambio de última hora."],
      ["Expresión", "tachar tareas", "划掉待办事项。例：Me motiva ir tachando tareas de la lista."],
      ["Verbo", "desconectar", "放空；不再想工作。例：El fin de semana intento desconectar del trabajo."],
      ["Adjetivo", "saturado/a", "忙不过来；信息过载。例：Últimamente me siento saturada de mensajes y tareas."],
      ["Expresión", "ir al grano", "直奔主题。例：Vamos al grano, que no tenemos mucho tiempo."],
      ["Expresión", "estar al tanto de", "了解；掌握。例：Quiero estar al tanto de los cambios del proyecto."],
      ["Expresión", "ganarle tiempo al día", "尽量把一天用满。例：Me levanto temprano para ganarle tiempo al día."],
      ["Expresión", "dar abasto", "忙得过来；应付得来。例：Con tanto trabajo junto, siento que no doy abasto."],
      ["Expresión", "llevarlo todo al día", "把事情都跟上。例：Me cuesta llevarlo todo al día cuando viajo mucho."],
      ["Expresión", "venirse abajo", "情绪垮掉。例：Intento no venirme abajo cuando algo sale mal."],
      ["Expresión", "cambiar el chip", "转换状态。例：Al llegar a casa necesito cambiar el chip y dejar de pensar en el trabajo."],
      ["Expresión", "tomarse un respiro", "喘口气。例：Después de esa semana, necesitaba tomarme un respiro."],
      ["Expresión", "tener la cabeza en otra parte", "心不在焉。例：Hoy tengo la cabeza en otra parte y no me concentro."],
      ["Adjetivo", "desbordado/a", "应接不暇的。例：Se sintió desbordada con tantos cambios seguidos."],
      ["Verbo", "sobrecargarse", "让自己负担过重。例：A veces me sobrecargo por no saber decir que no."],
      ["Expresión", "ir con retraso", "进度落后。例：Vamos con retraso, pero todavía podemos remontar."],
      ["Expresión", "poner en orden", "整理清楚。例：El domingo aprovecho para poner en orden mis notas y papeles."],
      ["Expresión", "arrancar el día", "开始一天。例：Necesito un café para arrancar el día con energía."],
      ["Expresión", "cerrar el día", "结束一天。例：Me gusta cerrar el día apuntando lo pendiente para mañana."],
      ["Expresión", "reorganizar prioridades", "重新调整优先级。例：Tuvimos que reorganizar prioridades por una urgencia."],
      ["Expresión", "recuperar energías", "恢复精力。例：El fin de semana fui al campo para recuperar energías."],
      ["Expresión", "ir tirando", "将就着过；凑合。例：No es la situación ideal, pero de momento voy tirando."],
      ["Expresión", "llevar un ritmo intenso", "保持高强度节奏。例：No puedo llevar un ritmo tan intenso durante meses."],
      ["Expresión", "quedarse sin margen", "没有余地。例：Si seguimos así, nos quedaremos sin margen de maniobra."],
    ]),
  },
  {
    slug: "trabajo-estudios",
    number: "02",
    title: "Trabajo y estudios",
    subtitle: "求职、工作能力、学业表达，偏 B1+ 实用",
    accent: "#d18a2f",
    points: [
      "不再停留在找工作、考试这类基础层。",
      "重点放在职责、表现、流程和能力。",
      "适合 DELE 口语与写作。",
      "很多词直接用于求职和职场对话。",
    ],
    why: "你会基础词以后，真正拉开差距的是这类更具体的工作学习表达。",
    core: [
      "优先记搭配，不要只记名词。",
      "很多表达都能进求职信、口头介绍和讨论题。",
      "重点是更自然地说职责、目标和表现。",
    ],
    focus: [
      "先记工作场景。",
      "再补学习与训练表达。",
      "注意抽象词和动词搭配。",
    ],
    cards: makeCards([
      ["Expresión", "desempeñar un puesto", "担任职位。例：Lleva años desempeñando un puesto de responsabilidad."],
      ["Expresión", "asumir responsabilidades", "承担责任。例：Está preparada para asumir más responsabilidades."],
      ["Verbo", "desenvolverse", "应对自如。例：Se desenvuelve bien en ambientes internacionales."],
      ["Verbo", "incorporarse", "入职；加入。例：Se incorporará al equipo a principios de junio."],
      ["Expresión", "optar a", "申请；争取。例：Quiere optar a una beca para estudiar fuera."],
      ["Expresión", "ampliar conocimientos", "扩展知识。例：Hice ese curso para ampliar conocimientos en marketing."],
      ["Expresión", "resolver incidencias", "处理问题。例：En mi trabajo tengo que resolver incidencias cada día."],
      ["Expresión", "presentar una candidatura", "提交申请。例：Ya he presentado mi candidatura para el máster."],
      ["Sustantivo", "la formación complementaria", "补充培训。例：La formación complementaria cuenta mucho en ese sector."],
      ["Sustantivo", "el entorno laboral", "工作环境。例：Busco un entorno laboral más flexible y estable."],
      ["Sustantivo", "el rendimiento", "表现；产出。例：Su rendimiento mejora cuando trabaja con objetivos claros."],
      ["Sustantivo", "la experiencia previa", "既往经验。例：Aunque no tiene experiencia previa, aprende muy rápido."],
      ["Sustantivo", "el contrato temporal", "临时合同。例：Empezó con un contrato temporal y luego lo renovaron."],
      ["Sustantivo", "el teletrabajo", "远程办公。例：El teletrabajo le permite organizar mejor su tiempo."],
      ["Verbo", "compaginar", "兼顾。例：Le cuesta compaginar el trabajo con los estudios."],
      ["Expresión", "llevar a cabo", "开展；执行。例：Tardaron meses en llevar a cabo el plan."],
      ["Expresión", "plantear objetivos", "设定目标。例：Es importante plantear objetivos realistas al empezar."],
      ["Expresión", "hacer seguimiento", "跟进。例：Cada semana hacemos seguimiento del progreso del proyecto."],
      ["Expresión", "entregar dentro del plazo", "按时提交。例：Consiguieron entregar todo dentro del plazo."],
      ["Expresión", "revisar a fondo", "彻底检查。例：Antes de enviarlo, conviene revisar el texto a fondo."],
      ["Expresión", "tomar la iniciativa", "主动。例：En esa empresa valoran mucho que tomes la iniciativa."],
      ["Expresión", "desenvolverse bajo presión", "在压力下工作。例：Dice que se desenvuelve bien bajo presión."],
      ["Expresión", "adquirir soltura", "变熟练。例：Con la práctica fui adquiriendo soltura al hablar."],
      ["Expresión", "justificar una decisión", "说明决定理由。例：Tuvo que justificar su decisión ante todo el equipo."],
      ["Expresión", "profundizar en", "深入学习。例：El año que viene quiere profundizar en análisis de datos."],
      ["Sustantivo", "la trayectoria profesional", "职业经历。例：Su trayectoria profesional es corta, pero bastante sólida."],
      ["Verbo", "especializarse", "专攻。例：Quiere especializarse en gestión cultural."],
      ["Expresión", "adquirir experiencia práctica", "获得实践经验。例：Ese puesto sirve para adquirir experiencia práctica."],
      ["Expresión", "coordinar un equipo", "协调团队。例：Nunca había coordinado un equipo tan grande."],
      ["Verbo", "supervisar", "监督。例：Le toca supervisar el trabajo de dos personas nuevas."],
      ["Verbo", "negociar", "协商。例：Tuvo que negociar las condiciones del contrato."],
      ["Sustantivo", "la carga de trabajo", "工作量。例：Este mes la carga de trabajo ha sido excesiva."],
      ["Expresión", "repartir tareas", "分配任务。例：Antes de empezar conviene repartir tareas con claridad."],
      ["Expresión", "tener soltura", "熟练自如。例：Ya tiene bastante soltura al atender al público."],
      ["Sustantivo", "la salida laboral", "就业方向。例：Ese máster ofrece más salidas laborales que el otro."],
      ["Verbo", "comprometerse", "承诺投入。例：Si aceptas el proyecto, tendrás que comprometerte de verdad."],
      ["Sustantivo", "el proceso de selección", "选拔流程。例：El proceso de selección fue más largo de lo esperado."],
      ["Expresión", "demostrar iniciativa", "展现主动性。例：En la entrevista intentó demostrar iniciativa y seguridad."],
      ["Expresión", "cumplir expectativas", "达到预期。例：El curso cumplió bastante bien mis expectativas."],
      ["Sustantivo", "la orientación laboral", "职业指导。例：Necesita orientación laboral para redefinir su perfil."],
      ["Expresión", "desarrollar competencias", "培养能力。例：Ese voluntariado me ayudó a desarrollar competencias útiles."],
      ["Expresión", "afrontar un reto", "面对挑战。例：Le apetecía cambiar de trabajo para afrontar un reto nuevo."],
      ["Sustantivo", "el curriculum vitae", "简历。例：Actualicé el curriculum vitae antes de enviar la solicitud."],
      ["Sustantivo", "el requisito", "要求；条件。例：Tener experiencia previa era un requisito imprescindible."],
      ["Sustantivo", "candidato/a", "候选人。例：Buscan a una candidata con iniciativa y experiencia práctica."],
      ["Sustantivo", "la jornada partida", "分段工时。例：No me compensa la jornada partida porque se alarga demasiado."],
      ["Sustantivo", "la jornada continua", "连续工时。例：Con jornada continua termino antes por la tarde."],
      ["Sustantivo", "la jornada intensiva", "紧缩工时。例：En verano muchas empresas adoptan la jornada intensiva."],
      ["Sustantivo", "la incorporación inmediata", "立即上岗。例：La oferta exigía incorporación inmediata."],
      ["Sustantivo", "el sindicato", "工会。例：El sindicato pidió mejores condiciones para toda la plantilla."],
      ["Verbo", "matricularse", "注册；报名。例：Quiere matricularse en un curso de español de negocios."],
      ["Sustantivo", "practicante", "实习生。例：Empezó como practicante y al cabo de unos meses la contrataron."],
      ["Sustantivo", "funcionario/a", "公务员。例：Su hermana se hizo funcionaria después de aprobar la oposición."],
      ["Sustantivo", "recepcionista", "前台；接待员。例：La recepcionista nos indicó dónde esperar."],
    ]),
  },
  {
    slug: "viajes-transporte",
    number: "03",
    title: "Viajes y transporte",
    subtitle: "不止旅游基础词，偏 B1+ 路线、问题与安排",
    accent: "#b58937",
    points: [
      "去掉最基础出行词，转向真实问题场景。",
      "更适合投诉、安排、确认和说明。",
      "适合口语叙述与邮件表达。",
      "很多词能直接用于旅行中的突发情况。",
    ],
    why: "基础的坐车订票你已经见过很多次了，真正缺的是更细的旅行表达。",
    core: [
      "优先记延误、改签、定位和路线变化。",
      "搭配比单个词更重要。",
      "例句尽量想成真实旅途问题。",
    ],
    focus: [
      "先记旅途问题。",
      "再记安排和确认。",
      "最后补环境与出行方式。",
    ],
    cards: makeCards([
      ["Sustantivo", "el desplazamiento", "出行；移动。例：El desplazamiento diario hasta el centro es bastante largo."],
      ["Verbo", "tramitar", "办理手续。例：Tuvimos que tramitar un cambio de billete."],
      ["Expresión", "gestionar una reserva", "处理预订。例：Ella se encargó de gestionar toda la reserva del viaje."],
      ["Expresión", "hacer escala", "中途经停。例：El vuelo hace escala en Lisboa antes de llegar."],
      ["Expresión", "quedarse tirado/a", "被困住；动不了。例：Nos quedamos tirados en la carretera por una avería."],
      ["Sustantivo", "la disponibilidad", "可用情况。例：No había disponibilidad en ningún hotel céntrico."],
      ["Sustantivo", "el alojamiento céntrico", "市中心住宿。例：Prefiero pagar más por un alojamiento céntrico."],
      ["Sustantivo", "el importe adicional", "额外费用。例：Nos cobraron un importe adicional por cambiar la fecha."],
      ["Expresión", "cancelar con antelación", "提前取消。例：Si cancelas con antelación, te devuelven casi todo."],
      ["Expresión", "modificar una reserva", "修改预订。例：Necesito modificar la reserva porque llegaremos un día más tarde."],
      ["Expresión", "perder la referencia", "失去方向感。例：Sin mapa perdimos la referencia enseguida."],
      ["Verbo", "ubicarse", "定位自己。例：Tardé un rato en ubicarme al salir del metro."],
      ["Verbo", "orientarse", "辨别方向。例：Le cuesta orientarse en ciudades grandes."],
      ["Sustantivo", "el entorno", "周边环境。例：El entorno del hotel era tranquilo y seguro."],
      ["Sustantivo", "la temporada alta", "旺季。例：Viajar en temporada alta sale muchísimo más caro."],
      ["Sustantivo", "el turismo masificado", "过度旅游。例：Ese barrio ya sufre bastante turismo masificado."],
      ["Expresión", "moverse con soltura", "行动熟练；活动方便。例：Después de dos días ya nos movíamos con soltura por la ciudad."],
      ["Sustantivo", "el desvío", "改道；绕行。例：Tuvimos que hacer un desvío por obras."],
      ["Sustantivo", "el inconveniente", "不便；问题。例：El único inconveniente era que no había ascensor."],
      ["Sustantivo", "la hora punta", "高峰时段。例：Evita esa línea en hora punta si puedes."],
      ["Verbo", "prever", "预估；预料。例：No habíamos previsto tanto tráfico."],
      ["Expresión", "consultar disponibilidad", "查询空位。例：Voy a consultar disponibilidad para el fin de semana."],
      ["Expresión", "viajar ligero/a", "轻装出行。例：Prefiero viajar ligera y no facturar maleta."],
      ["Expresión", "hacer un trayecto incómodo", "进行一段不舒服的行程。例：Con tantas maletas fue un trayecto incómodo."],
      ["Expresión", "tener buena conexión", "交通衔接好。例：Ese aeropuerto tiene buena conexión con el centro."],
      ["Sustantivo", "la incidencia", "意外问题；事故。例：Hubo una incidencia y el tren salió con una hora de retraso."],
      ["Expresión", "perderse una conexión", "错过衔接。例：Por la niebla nos perdimos la conexión a última hora."],
      ["Expresión", "rehacer el itinerario", "重做行程。例：Tuvimos que rehacer el itinerario por la tormenta."],
      ["Sustantivo", "el contratiempo", "波折；耽搁。例：A pesar del contratiempo, llegamos a tiempo al hotel."],
      ["Verbo", "desviarse", "偏离路线。例：El conductor tuvo que desviarse por un accidente."],
      ["Expresión", "dar con un sitio", "找到地方。例：Nos costó bastante dar con el apartamento."],
      ["Sustantivo", "la orientación", "辨别方向能力。例：Tiene buen sentido de la orientación incluso en ciudades nuevas."],
      ["Expresión", "dejar margen de maniobra", "留有余地。例：Siempre intento dejar margen de maniobra entre un plan y otro."],
      ["Sustantivo", "el acceso complicado", "不方便到达。例：El lugar era bonito, pero de acceso complicado."],
      ["Expresión", "moverse por libre", "自由行动。例：Preferimos movernos por libre en vez de ir con grupo."],
      ["Sustantivo", "el alojamiento provisional", "临时住处。例：Pasamos la primera noche en un alojamiento provisional."],
      ["Verbo", "reubicar", "重新安排位置。例：La compañía tuvo que reubicar a varios pasajeros."],
      ["Expresión", "tener el viaje condicionado por", "行程受…影响。例：Todo el viaje quedó condicionado por el mal tiempo."],
      ["Expresión", "hacer noche", "过夜。例：Como era tarde, decidimos hacer noche en un pueblo cercano."],
      ["Sustantivo", "la ruta alternativa", "备用路线。例：El navegador nos propuso una ruta alternativa más rápida."],
      ["Expresión", "viajar sobre la marcha", "边走边决定。例：A veces me gusta viajar sobre la marcha sin cerrar todo."],
      ["Sustantivo", "la reprogramación", "改期安排。例：La reprogramación del vuelo fue un caos total."],
      ["Sustantivo", "el mostrador de facturación", "值机柜台。例：Fuimos directos al mostrador de facturación al llegar al aeropuerto."],
      ["Sustantivo", "la tarjeta de embarque", "登机牌。例：Llevaba la tarjeta de embarque descargada en el móvil."],
      ["Sustantivo", "la puerta de embarque", "登机口。例：Cambiaron la puerta de embarque poco antes de llamar."],
      ["Verbo", "despegar", "起飞。例：El avión despegó con casi una hora de retraso."],
      ["Verbo", "aterrizar", "着陆。例：Aterrizamos de noche y apenas se veía la pista."],
      ["Verbo", "facturar", "托运行李。例：Como llevaba un bote grande, tuvo que facturar la maleta."],
      ["Sustantivo", "el billete de ida y vuelta", "往返票。例：Compró un billete de ida y vuelta para ahorrar algo."],
      ["Sustantivo", "la media pensión", "半膳宿。例：Reservaron media pensión para no preocuparse por la cena."],
      ["Sustantivo", "la pensión completa", "全膳宿。例：En temporada alta la pensión completa sube bastante de precio."],
      ["Sustantivo", "el alojamiento y desayuno (AD)", "住宿含早餐。例：Elegimos alojamiento y desayuno para comer fuera al mediodía."],
      ["Sustantivo", "auxiliar de vuelo", "乘务员。例：El auxiliar de vuelo nos ayudó con el equipaje de mano."],
      ["Expresión", "todos los caminos llevan a Roma", "条条大路通罗马。例：No hace falta obsesionarse con una sola opción; todos los caminos llevan a Roma."],
      ["Expresión", "ir sobre ruedas", "进展顺利。例：Después del primer retraso, el resto del viaje fue sobre ruedas."],
    ]),
  },
  {
    slug: "vivienda-ciudad",
    number: "04",
    title: "Vivienda y ciudad",
    subtitle: "住房与城市问题，偏 B1+ 描述和抱怨",
    accent: "#8f7d4e",
    points: [
      "不再只说房租和房间，而是说条件、缺陷和环境。",
      "适合描述住处、讨论城市问题。",
      "很适合 DELE 写作和口语题。",
      "注意形容词和名词搭配。",
    ],
    why: "基础的 casa, piso 这种你早就知道了，真正需要的是更细致地说明问题。",
    core: [
      "优先记住房条件和城市压力。",
      "很多表达适合抱怨、比较和解释。",
      "例句尽量代入租房或搬家场景。",
    ],
    focus: [
      "先记住处条件。",
      "再记城市问题。",
      "最后补社区和费用。",
    ],
    cards: makeCards([
      ["Expresión", "reformar a fondo", "彻底翻修。例：Compraron un piso antiguo y lo reformaron a fondo."],
      ["Sustantivo", "el suministro", "水电等供应。例：Este mes subieron todos los suministros básicos."],
      ["Sustantivo", "la cuota de comunidad", "物业费。例：La cuota de comunidad es más alta de lo que esperaba."],
      ["Sustantivo", "la convivencia complicada", "共同生活不顺。例：La convivencia se volvió complicada por el ruido constante."],
      ["Adjetivo", "insonorizado/a", "隔音好的。例：Busco un piso bien insonorizado porque trabajo desde casa."],
      ["Adjetivo", "bien aislado/a", "保温隔热好的。例：El piso está bien aislado y en invierno se nota."],
      ["Sustantivo", "el desperfecto", "房屋损坏。例：Anotamos todos los desperfectos antes de firmar."],
      ["Verbo", "acondicionar", "调整；布置好。例：Tardaron semanas en acondicionar el local."],
      ["Sustantivo", "la distribución", "布局。例：La distribución del piso no aprovecha bien el espacio."],
      ["Expresión", "la vivienda asequible", "负担得起的住房。例：Cada vez cuesta más encontrar vivienda asequible."],
      ["Sustantivo", "el acceso", "通达；入口。例：El acceso al transporte público es bastante cómodo."],
      ["Sustantivo", "la zona residencial", "住宅区。例：Prefieren vivir en una zona residencial y más silenciosa."],
      ["Sustantivo", "el ruido constante", "持续噪音。例：No soportaba el ruido constante de la avenida."],
      ["Sustantivo", "las obras", "施工。例：Llevan meses con obras justo debajo de casa."],
      ["Verbo", "rehabilitar", "修复；整修。例：El ayuntamiento quiere rehabilitar varios edificios históricos."],
      ["Expresión", "ceder espacio", "腾出空间。例：Tuvimos que ceder espacio en el salón para montar la mesa."],
      ["Expresión", "aprovechar el espacio", "充分利用空间。例：Los muebles plegables ayudan a aprovechar el espacio."],
      ["Sustantivo", "la ventilación", "通风。例：Para mí la ventilación es más importante que el tamaño."],
      ["Sustantivo", "el mantenimiento", "维护。例：El mantenimiento del edificio deja bastante que desear."],
      ["Sustantivo", "el coste de vida", "生活成本。例：El coste de vida en esa ciudad ha subido muchísimo."],
      ["Sustantivo", "el desplazamiento diario", "日常通勤。例：No quiero hacer un desplazamiento diario de una hora y media."],
      ["Sustantivo", "el entorno urbano", "城市环境。例：Me interesa más el entorno urbano que el tamaño del piso."],
      ["Sustantivo", "la inseguridad", "治安问题；不安全感。例：Mucha gente se queja de la inseguridad del barrio."],
      ["Sustantivo", "la saturación del tráfico", "交通拥堵。例：La saturación del tráfico empeora mucho a partir de las seis."],
      ["Expresión", "el alquiler abusivo", "过高租金。例：Cada vez se habla más del problema del alquiler abusivo."],
      ["Sustantivo", "la rehabilitación urbana", "城市整修。例：El centro histórico necesita un plan serio de rehabilitación urbana."],
      ["Sustantivo", "la accesibilidad", "无障碍通达。例：Ese edificio antiguo tiene problemas de accesibilidad."],
      ["Expresión", "quedarse pequeño", "显得不够用。例：El piso se nos ha quedado pequeño con el tiempo."],
      ["Expresión", "necesitar una reforma", "需要翻修。例：La cocina está bien situada, pero necesita una reforma."],
      ["Sustantivo", "la distribución poco práctica", "不实用布局。例：La distribución poco práctica nos hizo descartarlo."],
      ["Adjetivo", "deteriorado/a", "破旧的。例：La fachada está bastante deteriorada."],
      ["Sustantivo", "la vivienda vacía", "空置住房。例：En el barrio hay demasiada vivienda vacía."],
      ["Sustantivo", "la densidad de población", "人口密度。例：La densidad de población se nota mucho en esa zona."],
      ["Expresión", "renunciar al centro", "放弃住市中心。例：Muchos jóvenes renuncian al centro por el precio."],
      ["Sustantivo", "la periferia", "城市边缘地带。例：Terminó mudándose a la periferia para ahorrar."],
      ["Sustantivo", "el equipamiento urbano", "城市配套设施。例：Falta equipamiento urbano en los barrios nuevos."],
      ["Expresión", "ganar en comodidad", "提升舒适度。例：Con la reforma ganaron mucho en comodidad."],
      ["Expresión", "perder calidad de vida", "生活质量下降。例：Con tanto ruido acabas perdiendo calidad de vida."],
      ["Sustantivo", "la falta de servicios", "服务不足。例：La falta de servicios básicos preocupa a los vecinos."],
      ["Verbo", "encarecerse", "变贵。例：Todo se ha encarecido muchísimo en los últimos años."],
      ["Expresión", "estar bien aprovechado", "空间利用得好。例：Es un piso pequeño, pero muy bien aprovechado."],
      ["Sustantivo", "la zona tensionada", "住房紧张区域。例：Ese distrito ya se considera una zona tensionada."],
      ["Sustantivo", "el ascensor", "电梯。例：El piso estaba bien, pero no tenía ascensor."],
      ["Sustantivo", "el portal", "门厅；楼门口。例：Quedamos en el portal para subir juntos."],
      ["Sustantivo", "el patio", "庭院；天井。例：La habitación da a un patio interior muy tranquilo."],
      ["Sustantivo", "el sótano", "地下室。例：Guardan las bicis en el sótano del edificio."],
      ["Sustantivo", "la estantería", "书架；置物架。例：Pusimos una estantería para aprovechar mejor esa pared."],
      ["Sustantivo", "la cocina vitrocerámica", "陶瓷电炉。例：La cocina vitrocerámica es práctica, aunque tarda en enfriarse."],
      ["Adjetivo", "bien comunicado/a", "交通便利的。例：Buscan un piso pequeño pero bien comunicado."],
      ["Sustantivo", "la glorieta", "环岛；街心广场。例：Nos vemos junto a la glorieta de la estación."],
      ["Sustantivo", "el trasbordo", "换乘。例：Hay que hacer un trasbordo para llegar al barrio nuevo."],
      ["Sustantivo", "el aparcamiento", "停车场；停车位。例：Encontrar aparcamiento aquí por la noche es dificilísimo."],
      ["Sustantivo", "el atasco", "堵车。例：Salimos antes para evitar el atasco de la mañana."],
      ["Sustantivo", "el casco histórico", "历史城区。例：El casco histórico siempre está lleno de gente los fines de semana."],
      ["Sustantivo", "la zona industrial", "工业区。例：Su oficina se ha mudado a una zona industrial en las afueras."],
      ["Sustantivo", "la boca de metro", "地铁口。例：Hay una boca de metro justo enfrente del edificio."],
      ["Expresión", "estar en el quinto pino", "在很远的地方。例：Ese piso está en el quinto pino y sin transporte directo."],
      ["Expresión", "tirar la casa por la ventana", "大手大脚花钱。例：Para amueblar el piso no queremos tirar la casa por la ventana."],
    ]),
  },
  {
    slug: "salud-cuerpo",
    number: "05",
    title: "Salud y cuerpo",
    subtitle: "身体和健康不再停留在基础病症，偏 B1+",
    accent: "#5e8f63",
    points: [
      "从简单不舒服，过渡到状态、预防和恢复。",
      "适合描述健康、压力和习惯。",
      "既能用于看病，也能用于生活方式讨论。",
      "优先记高频抽象词。",
    ],
    why: "B1 以上的健康表达不只是头痛发烧，而是能更完整地讲状态和恢复过程。",
    core: [
      "先记症状和恢复。",
      "再补预防、习惯、情绪健康。",
      "注意很多表达都适合写作。",
    ],
    focus: [
      "先记状态描述。",
      "再记医疗和预防。",
      "最后补情绪健康词。",
    ],
    cards: makeCards([
      ["Expresión", "recuperarse del todo", "完全恢复。例：Todavía no me he recuperado del todo del resfriado."],
      ["Verbo", "padecer", "患有；遭受。例：Padece dolores de espalda desde hace años."],
      ["Expresión", "aliviar los síntomas", "缓解症状。例：Ese medicamento ayuda a aliviar los síntomas."],
      ["Expresión", "hacerse una revisión", "做检查。例：Debería hacerme una revisión antes del verano."],
      ["Sustantivo", "la molestia", "不适；小痛。例：Al principio era solo una molestia, pero fue a más."],
      ["Sustantivo", "el malestar", "不适感。例：Suspendió el viaje por un malestar repentino."],
      ["Expresión", "llevar una vida sedentaria", "久坐生活。例：Llevar una vida sedentaria acaba pasando factura."],
      ["Sustantivo", "el agotamiento", "精疲力尽。例：Después de varias semanas así, terminó con agotamiento."],
      ["Sustantivo", "la tensión muscular", "肌肉紧张。例：Tengo bastante tensión muscular en el cuello."],
      ["Sustantivo", "el chequeo", "体检。例：Aprovechó las vacaciones para hacerse un chequeo completo."],
      ["Sustantivo", "el diagnóstico", "诊断。例：El diagnóstico llegó más tarde de lo esperado."],
      ["Verbo", "prevenir", "预防。例：Es mejor prevenir que esperar a sentirse peor."],
      ["Verbo", "recaer", "复发。例：Volvió a recaer por no descansar lo suficiente."],
      ["Adjetivo", "convaleciente", "恢复中的。例：Estuvo convaleciente casi dos semanas."],
      ["Sustantivo", "el bienestar emocional", "情绪健康。例：El bienestar emocional también forma parte de la salud."],
      ["Sustantivo", "la ansiedad", "焦虑。例：En épocas de exámenes le aumenta la ansiedad."],
      ["Expresión", "sobrellevar el estrés", "应对压力。例：Está aprendiendo a sobrellevar el estrés mejor que antes."],
      ["Expresión", "adoptar hábitos saludables", "养成健康习惯。例：Quiere adoptar hábitos saludables de forma realista."],
      ["Expresión", "moderar el consumo", "控制摄入。例：Me recomendaron moderar el consumo de café."],
      ["Sustantivo", "la falta de apetito", "没胃口。例：La falta de apetito duró solo un par de días."],
      ["Verbo", "hidratarse", "补水。例：Con este calor es fundamental hidratarse bien."],
      ["Expresión", "notar mejoría", "感觉好转。例：Empecé a notar mejoría al tercer día."],
      ["Sustantivo", "el tratamiento", "治疗方案。例：Siguió el tratamiento al pie de la letra."],
      ["Verbo", "descartar", "排除。例：Primero quisieron descartar algo más grave."],
      ["Sustantivo", "la recuperación", "恢复。例：La recuperación fue lenta, pero constante."],
      ["Sustantivo", "la revisión médica", "体检复查。例：Le toca una revisión médica el mes que viene."],
      ["Expresión", "tener el cuerpo resentido", "身体吃不消。例：Después del viaje tenía el cuerpo bastante resentido."],
      ["Expresión", "coger fuerzas", "恢复体力。例：Paró un momento para coger fuerzas y seguir."],
      ["Sustantivo", "la bajada de tensión", "低血压发作。例：Le dio una bajada de tensión en plena calle."],
      ["Adjetivo", "hinchado/a", "肿胀的。例：Tenía el tobillo hinchado por el golpe."],
      ["Sustantivo", "el seguimiento médico", "医疗跟进。例：Necesita seguimiento médico durante unas semanas."],
      ["Verbo", "evolucionar", "发展；好转。例：Por suerte ha evolucionado bastante bien."],
      ["Expresión", "recetar algo", "开药。例：Le recetaron un antibiótico y reposo."],
      ["Sustantivo", "el efecto secundario", "副作用。例：Le preocupaban los posibles efectos secundarios."],
      ["Expresión", "hacer reposo", "静养。例：Le recomendaron hacer reposo al menos dos días."],
      ["Sustantivo", "la inflamación", "炎症。例：La inflamación bajó después del tratamiento."],
      ["Expresión", "perder el apetito", "胃口变差。例：Cuando se pone nervioso, pierde el apetito."],
      ["Verbo", "fortalecer", "增强。例：Quiere fortalecer la espalda con ejercicios suaves."],
      ["Sustantivo", "la postura", "姿势。例：Le dijeron que corrigiera la postura al sentarse."],
      ["Expresión", "pasar factura", "让人吃不消。例：Tantos meses sin descansar acabaron pasándole factura."],
      ["Sustantivo", "el equilibrio emocional", "情绪平衡。例：Dormir mejor le ayuda a recuperar el equilibrio emocional."],
      ["Expresión", "sentirse al límite", "感觉快撑不住。例：Hubo una época en la que se sintió al límite."],
      ["Sustantivo", "cirujano/a", "外科医生。例：El cirujano explicó en qué consistía la operación."],
      ["Sustantivo", "ginecólogo/a", "妇科医生。例：Pidió cita con la ginecóloga para una revisión."],
      ["Sustantivo", "oftalmólogo/a", "眼科医生。例：El oftalmólogo le cambió la graduación."],
      ["Sustantivo", "traumatólogo/a", "创伤科医生。例：El traumatólogo le recomendó reposo y fisioterapia."],
      ["Sustantivo", "paciente", "病人。例：La paciente tuvo que esperar casi una hora."],
      ["Sustantivo", "la consulta", "问诊；诊室。例：Entró en la consulta cuando la llamaron."],
      ["Sustantivo", "la vacuna", "疫苗。例：Le pusieron la vacuna antes del viaje."],
      ["Sustantivo", "el análisis de sangre", "血检。例：Le pidieron un análisis de sangre para confirmar el diagnóstico."],
      ["Sustantivo", "el análisis de orina", "尿检。例：También le hicieron un análisis de orina esa misma mañana."],
      ["Sustantivo", "el termómetro", "体温计。例：No encontraba el termómetro cuando empezó a tener fiebre."],
      ["Sustantivo", "la cápsula", "胶囊。例：Tiene que tomar una cápsula después de cenar."],
      ["Sustantivo", "el jarabe", "糖浆。例：El médico le mandó jarabe para la tos."],
      ["Expresión", "romperse un hueso", "骨折。例：Se cayó esquiando y acabó por romperse un hueso."],
      ["Sustantivo", "médico/a de familia", "家庭医生。例：Primero consultó con su médica de familia."],
      ["Sustantivo", "la farmacia de guardia", "值班药房。例：Fuimos a la farmacia de guardia porque era domingo."],
      ["Sustantivo", "fisioterapeuta", "理疗师。例：El fisioterapeuta le enseñó varios ejercicios suaves."],
      ["Sustantivo", "el centro de salud", "社区健康中心。例：El centro de salud del barrio abre a las ocho."],
      ["Expresión", "estar como un roble", "身体硬朗。例：Con su edad sigue estando como un roble."],
      ["Expresión", "tener salud de hierro", "身体非常好。例：Siempre presume de tener salud de hierro."],
    ]),
  },
  {
    slug: "compras-consumo",
    number: "06",
    title: "Compras y consumo",
    subtitle: "消费不只会买卖，偏 B1+ 判断与选择",
    accent: "#4b8b8e",
    points: [
      "重点放在比较、判断、售后和消费观念。",
      "适合描述选择过程和抱怨。",
      "很多词是 B1 以上很常见的生活词。",
      "优先记价格和评价搭配。",
    ],
    why: "你会 comprar 不够，真正好用的是这些更像现实选择场景的词。",
    core: [
      "先记判断是否划算。",
      "再记售后和广告表达。",
      "最后补消费方式和预算词。",
    ],
    focus: [
      "先记选择和比较。",
      "再记售后细节。",
      "最后补消费观念。",
    ],
    cards: makeCards([
      ["Expresión", "comparar prestaciones", "比较性能。例：Antes de comprarlo, comparé prestaciones y opiniones."],
      ["Expresión", "ajustarse al presupuesto", "符合预算。例：Nos gustaba más el otro, pero este se ajusta al presupuesto."],
      ["Verbo", "compensar", "值得；补偿。例：No sé si pagar más compensa en este caso."],
      ["Sustantivo", "el coste adicional", "附加成本。例：El envío rápido supone un coste adicional bastante alto."],
      ["Sustantivo", "la relación calidad-precio", "性价比。例：Por ese precio, la relación calidad-precio es muy buena."],
      ["Sustantivo", "el consumo responsable", "理性消费。例：Cada vez me interesa más el consumo responsable."],
      ["Sustantivo", "la compra impulsiva", "冲动消费。例：Intento evitar la compra impulsiva cuando estoy cansada."],
      ["Sustantivo", "el gasto innecesario", "不必要开销。例：Revisé mis cuentas y vi mucho gasto innecesario."],
      ["Sustantivo", "la devolución inmediata", "即时退款；立刻退货。例：Por suerte me hicieron la devolución inmediata."],
      ["Sustantivo", "la garantía ampliada", "延保。例：No creo que merezca la pena pagar la garantía ampliada."],
      ["Expresión", "la letra pequeña", "细则；小字条款。例：Siempre conviene leer la letra pequeña."],
      ["Expresión", "valorar una reseña", "参考评价。例：Antes de decidir, suelo valorar varias reseñas."],
      ["Sustantivo", "el plazo de entrega", "送达时限。例：El plazo de entrega era más largo de lo que decía la web."],
      ["Expresión", "agotar existencias", "卖光库存。例：Esa promoción agotó existencias en pocas horas."],
      ["Verbo", "reembolsar", "退款。例：La tienda tardó una semana en reembolsarme el dinero."],
      ["Verbo", "rebajar", "降价。例：Al final rebajaron un poco el precio final."],
      ["Expresión", "el presupuesto ajustado", "预算很紧。例：Este mes tengo un presupuesto bastante ajustado."],
      ["Expresión", "salir rentable", "划算。例：Comprar a granel suele salir más rentable."],
      ["Sustantivo", "el comercio local", "本地商家。例：Intento apoyar más el comercio local del barrio."],
      ["Sustantivo", "la financiación", "分期；融资。例：Ofrecen financiación, pero yo prefiero pagarlo de una vez."],
      ["Sustantivo", "el consumo excesivo", "过度消费。例：El consumo excesivo termina generando más estrés que satisfacción."],
      ["Sustantivo", "la publicidad engañosa", "误导广告。例：Ese anuncio me parece un caso de publicidad engañosa."],
      ["Verbo", "priorizar", "优先考虑。例：Ahora priorizo comprar menos, pero mejor."],
      ["Expresión", "renunciar a una compra", "放弃购买。例：Renuncié a la compra cuando vi el precio final."],
      ["Expresión", "aprovechar una oferta", "抓住优惠。例：Aproveché la oferta porque llevaba meses esperando."],
      ["Expresión", "dejarse llevar por", "被…带着走。例：A veces nos dejamos llevar por la publicidad sin pensar."],
      ["Sustantivo", "la decisión de compra", "购买决定。例：La opinión de otros influye mucho en la decisión de compra."],
      ["Sustantivo", "la necesidad real", "真实需求。例：Antes de pagar, me pregunto si responde a una necesidad real."],
      ["Sustantivo", "el precio inflado", "虚高价格。例：Da la impresión de que el precio está inflado."],
      ["Expresión", "hacer una reclamación", "提出投诉。例：Tuve que hacer una reclamación por escrito."],
      ["Sustantivo", "la política de devoluciones", "退货政策。例：La política de devoluciones era bastante confusa."],
      ["Sustantivo", "la atención posventa", "售后服务。例：La atención posventa fue mucho mejor de lo esperado."],
      ["Expresión", "comparar condiciones", "比较条件。例：Conviene comparar condiciones antes de firmar nada."],
      ["Sustantivo", "el embalaje", "包装。例：El producto llegó con el embalaje roto."],
      ["Verbo", "encargar", "订购。例：Encargamos el mueble porque no quedaban unidades en tienda."],
      ["Sustantivo", "el recargo", "附加费。例：Nos aplicaron un recargo por pagar a plazos."],
      ["Expresión", "recortar gastos", "削减开销。例：Este año estamos intentando recortar gastos en ocio."],
      ["Sustantivo", "la compra consciente", "有意识消费。例：Cada vez me interesa más la compra consciente."],
      ["Expresión", "no salir a cuenta", "不划算。例：Con los gastos extra, al final no sale a cuenta."],
      ["Sustantivo", "el valor añadido", "附加价值。例：Ese producto tiene poco valor añadido para lo que cuesta."],
      ["Verbo", "ajustar", "调整。例：Tuvimos que ajustar el presupuesto al ver los precios reales."],
      ["Expresión", "ceñirse a un presupuesto", "严格按预算来。例：Si no me ciño a un presupuesto, gasto demasiado."],
      ["Expresión", "pagar con tarjeta", "刷卡支付。例：En esa tienda solo se puede pagar con tarjeta a partir de diez euros."],
      ["Sustantivo", "el préstamo", "贷款；借款。例：Pidieron un préstamo para abrir el negocio."],
      ["Expresión", "de rayas", "条纹的。例：Eligió una camisa de rayas para la entrevista."],
      ["Verbo", "probarse", "试穿。例：Prefiero probarme la ropa antes de decidir."],
      ["Expresión", "quedar bien/mal", "合身/不合身。例：La chaqueta me queda bien de hombros, pero larga de mangas."],
      ["Expresión", "a la moda/pasado de moda", "流行的/过时的。例：No me importa si está a la moda o pasado de moda."],
      ["Expresión", "de cuadros", "格子的。例：Nunca me han gustado demasiado las camisas de cuadros."],
      ["Sustantivo", "el recibo", "收据。例：Guarda el recibo por si luego cambias de opinión."],
      ["Sustantivo", "el escaparate", "橱窗。例：Ese abrigo me llamó la atención en el escaparate."],
      ["Sustantivo", "el mostrador", "柜台。例：Primero tienes que pagar en el mostrador."],
      ["Expresión", "pagar en metálico", "现金支付。例：Prefiero pagar en metálico cuando llevo un presupuesto fijo."],
      ["Adjetivo", "estampado/a", "印花的。例：Se compró un vestido estampado para el verano."],
      ["Expresión", "estar por las nubes", "贵得离谱。例：Los precios en esa zona están por las nubes."],
      ["Expresión", "estar sin blanca", "身无分文。例：Después de las vacaciones me quedé sin blanca."],
      ["Sustantivo", "la tarjeta de débito", "借记卡。例：Perdió la tarjeta de débito y tuvo que bloquearla."],
      ["Sustantivo", "la transferencia", "转账。例：Me hicieron la transferencia al día siguiente."],
    ]),
  },
  {
    slug: "relaciones-emociones",
    number: "07",
    title: "Relaciones y emociones",
    subtitle: "从基础感受升级到关系处理与冲突表达",
    accent: "#95658f",
    points: [
      "去掉最基础的喜欢讨厌，转向关系细节。",
      "适合口语讲经历和讨论人际问题。",
      "高频但不算太基础。",
      "很多表达都很适合手机反复刷。",
    ],
    why: "B1 往上最明显的差别之一，就是能不能讲清楚关系和情绪变化。",
    core: [
      "优先记冲突、理解和修复关系的表达。",
      "例句尽量代入真实关系场景。",
      "这组词很适合做口语素材。",
    ],
    focus: [
      "先记冲突和误会。",
      "再记支持与信任。",
      "最后补复杂情绪。",
    ],
    cards: makeCards([
      ["Sustantivo", "el malentendido", "误会。例：Todo empezó por un malentendido bastante tonto."],
      ["Expresión", "guardar rencor", "记仇。例：No me gusta guardar rencor durante mucho tiempo."],
      ["Expresión", "ponerse a la defensiva", "变得防备。例：Se puso a la defensiva en cuanto escuchó la crítica."],
      ["Verbo", "sincerarse", "坦白说。例：Una tarde se sinceró y me contó lo que le pasaba."],
      ["Expresión", "apoyar incondicionalmente", "无条件支持。例：Su familia la apoyó incondicionalmente."],
      ["Expresión", "marcar límites", "设立界限。例：Con algunas personas es importante marcar límites."],
      ["Expresión", "dar por hecho", "想当然。例：No des por hecho que la otra persona piensa como tú."],
      ["Expresión", "sentirse desplazado/a", "感到被边缘化。例：A veces se siente desplazado cuando nadie le consulta nada."],
      ["Expresión", "generar confianza", "建立信任。例：La sinceridad ayuda mucho a generar confianza."],
      ["Expresión", "tener roces", "有摩擦。例：Es normal tener pequeños roces cuando compartes piso."],
      ["Expresión", "estar a la altura", "达到期望。例：Le preocupaba no estar a la altura del puesto."],
      ["Expresión", "tomarse algo a pecho", "太往心里去。例：Se toma las críticas demasiado a pecho."],
      ["Verbo", "desahogarse", "倾诉。例：Necesitaba desahogarse con alguien de confianza."],
      ["Expresión", "llegar a un acuerdo", "达成一致。例：Nos costó, pero al final llegamos a un acuerdo."],
      ["Expresión", "enfriarse una relación", "关系变淡。例：La relación se fue enfriando con el tiempo."],
      ["Expresión", "asumir un error", "承认错误。例：Le costó, pero acabó asumiendo su error."],
      ["Expresión", "hacer una crítica constructiva", "提出建设性批评。例：Intentó hacer una crítica constructiva sin herirla."],
      ["Expresión", "mostrarse distante", "显得疏远。例：Últimamente se muestra más distante que antes."],
      ["Expresión", "valorar el esfuerzo ajeno", "认可他人努力。例：No siempre sabemos valorar el esfuerzo ajeno."],
      ["Verbo", "reconciliarse", "和解。例：Se reconciliaron después de hablar con calma."],
      ["Sustantivo", "la decepción", "失望。例：La decepción fue grande, pero aprendió mucho."],
      ["Sustantivo", "la inseguridad", "不安；缺乏安全感。例：A veces su inseguridad afecta a la relación."],
      ["Sustantivo", "la complicidad", "默契。例：Entre ellos hay una complicidad muy difícil de fingir."],
      ["Verbo", "mediar", "调解。例：Tuvo que mediar entre dos compañeros enfrentados."],
      ["Expresión", "gestionar un conflicto", "处理冲突。例：No todo el mundo sabe gestionar un conflicto con madurez."],
      ["Expresión", "echar en cara", "翻旧账；责备。例：No sirve de nada echarse las cosas en cara a cada momento."],
      ["Expresión", "ponerse en el lugar del otro", "站在对方角度。例：Falta ponerse en el lugar del otro antes de juzgar."],
      ["Sustantivo", "el desgaste emocional", "情绪消耗。例：La situación provocó bastante desgaste emocional."],
      ["Verbo", "malinterpretar", "误解。例：No malinterpretes su silencio; está simplemente agotado."],
      ["Expresión", "romper el hielo", "打破僵局。例：A él se le da bien romper el hielo en grupos nuevos."],
      ["Expresión", "tener un gesto", "做出体贴举动。例：Tuvo un gesto muy bonito en un momento difícil."],
      ["Sustantivo", "la falta de empatía", "缺乏共情。例：Lo que más le dolió fue la falta de empatía."],
      ["Expresión", "tomar distancia", "拉开距离。例：Decidió tomar distancia para pensar con calma."],
      ["Expresión", "sentirse cuestionado/a", "感到被质疑。例：Se sintió cuestionada delante de todo el mundo."],
      ["Verbo", "reprochar", "责怪。例：Le reprochó no haber dicho nada antes."],
      ["Sustantivo", "la afinidad", "契合度。例：Entre ellos hubo afinidad desde el primer día."],
      ["Expresión", "pasar por alto", "忽略。例：No deberíamos pasar por alto cómo se siente la otra persona."],
      ["Verbo", "distanciarse", "疏远。例：Poco a poco se fue distanciando del grupo."],
      ["Expresión", "sentar mal", "让人不舒服；介意。例：Le sentó mal que no contaran con él."],
      ["Expresión", "dar espacio", "给空间。例：A veces lo mejor es dar espacio y esperar."],
      ["Sustantivo", "la tensión acumulada", "积累的紧张感。例：La tensión acumulada acabó explotando en una discusión."],
      ["Expresión", "poner límites sanos", "设定健康界限。例：Está aprendiendo a poner límites sanos en sus relaciones."],
    ]),
  },
  {
    slug: "tecnologia-medios",
    number: "08",
    title: "Tecnología y medios",
    subtitle: "信息、平台与数字生活，偏 B1+ 高频",
    accent: "#5674a6",
    points: [
      "去掉最基础设备词，补更真实的数码表达。",
      "适合讨论媒体、网络习惯、真假信息。",
      "很多词非常实用。",
      "手机上学这一组复用率会很高。",
    ],
    why: "你日常接触手机和网络很多，这类词最容易高频复现、最快进脑子。",
    core: [
      "优先记信息判断和平台操作。",
      "不要只记名词，要记动作。",
      "很多表达适合观点题。",
    ],
    focus: [
      "先记信息处理。",
      "再记账号和平台操作。",
      "最后补数字生活习惯词。",
    ],
    cards: makeCards([
      ["Expresión", "verificar una fuente", "核实来源。例：Antes de compartirlo, conviene verificar la fuente."],
      ["Verbo", "difundir", "传播。例：La noticia se difundió rapidísimo por redes."],
      ["Sustantivo", "la privacidad", "隐私。例：Cada vez me preocupa más la privacidad en internet."],
      ["Sustantivo", "la sobreinformación", "信息过载。例：Con tanta sobreinformación, a veces cuesta pensar con calma."],
      ["Sustantivo", "la herramienta digital", "数字工具。例：Usamos una herramienta digital para coordinarnos mejor."],
      ["Verbo", "almacenar", "存储。例：Prefiero almacenar los documentos importantes en la nube."],
      ["Sustantivo", "el fallo técnico", "技术故障。例：La videollamada se cortó por un fallo técnico."],
      ["Expresión", "recuperar archivos", "恢复文件。例：Por suerte pudieron recuperar casi todos los archivos."],
      ["Sustantivo", "el consumo de contenido", "内容消费。例：Ha cambiado mucho mi consumo de contenido este año."],
      ["Sustantivo", "el algoritmo", "算法。例：A veces el algoritmo te muestra siempre lo mismo."],
      ["Expresión", "contrastar datos", "核对信息。例：Hay que contrastar datos antes de sacar conclusiones."],
      ["Sustantivo", "la plataforma", "平台。例：Esa plataforma tiene un sistema bastante intuitivo."],
      ["Expresión", "bloquear notificaciones", "屏蔽通知。例：Por la noche suelo bloquear notificaciones."],
      ["Verbo", "editar", "编辑。例：Editó el vídeo en el móvil durante el viaje."],
      ["Verbo", "automatizar", "自动化。例：Quieren automatizar algunas tareas repetitivas."],
      ["Sustantivo", "la huella digital", "数字痕迹。例：Dejamos mucha huella digital sin darnos cuenta."],
      ["Expresión", "navegar con fluidez", "流畅浏览。例：Con esa conexión ya se puede navegar con fluidez."],
      ["Expresión", "el acceso restringido", "受限访问。例：Ese documento tiene acceso restringido."],
      ["Expresión", "la copia de seguridad", "备份。例：Haz una copia de seguridad antes de actualizar nada."],
      ["Sustantivo", "la suscripción", "订阅。例：Cancelé varias suscripciones que casi no usaba."],
      ["Verbo", "desinstalar", "卸载。例：Desinstalé la aplicación porque ocupaba demasiado espacio."],
      ["Expresión", "el uso excesivo", "过度使用。例：El uso excesivo del móvil afecta a la concentración."],
      ["Expresión", "compartir ubicación", "分享定位。例：Le compartí mi ubicación para que me encontrara."],
      ["Verbo", "silenciar", "静音。例：Silencié el grupo porque no paraban de escribir."],
      ["Expresión", "filtrar información", "泄露；筛选信息。例：Temen que alguien haya filtrado información privada."],
      ["Sustantivo", "la brecha digital", "数字鸿沟。例：La brecha digital sigue siendo un problema real."],
      ["Verbo", "viralizarse", "疯传。例：El vídeo se viralizó en menos de un día."],
      ["Expresión", "consumir contenido", "消费内容。例：Paso demasiado tiempo consumiendo contenido sin darme cuenta."],
      ["Sustantivo", "la cuenta verificada", "认证账号。例：La noticia salió en una cuenta verificada."],
      ["Sustantivo", "la saturación informativa", "信息过载。例：La saturación informativa termina generando cansancio."],
      ["Expresión", "perder tiempo deslizando", "不断下滑浪费时间。例：Puedo perder mucho tiempo deslizando sin objetivo."],
      ["Expresión", "programar una publicación", "定时发布。例：Programó la publicación para la hora de más tráfico."],
      ["Sustantivo", "la interacción", "互动。例：Esa cuenta genera mucha interacción con poco contenido."],
      ["Expresión", "quedarse colgado/a", "卡住；死机。例：La página se quedó colgada justo al pagar."],
      ["Expresión", "actualizar datos", "更新资料。例：Tuve que actualizar mis datos personales."],
      ["Sustantivo", "el historial", "历史记录。例：Borré el historial para liberar espacio."],
      ["Expresión", "tener acceso restringido", "访问受限。例：Solo algunas personas tienen acceso restringido a esa carpeta."],
      ["Sustantivo", "la verificación en dos pasos", "双重验证。例：Activé la verificación en dos pasos por seguridad."],
      ["Verbo", "respaldar", "备份。例：Conviene respaldar las fotos importantes cada cierto tiempo."],
      ["Expresión", "hacer una captura", "截图。例：Haz una captura por si luego cambia la información."],
      ["Sustantivo", "la navegación intuitiva", "操作直观。例：La web tiene una navegación bastante intuitiva."],
      ["Expresión", "controlar el tiempo en pantalla", "控制屏幕时间。例：Estoy intentando controlar mejor el tiempo en pantalla."],
      ["Sustantivo", "la agencia de prensa", "通讯社。例：La agencia de prensa difundió la noticia de madrugada."],
      ["Sustantivo", "el contestador", "答录机。例：Si no te contesta, deja un mensaje en el contestador."],
      ["Sustantivo", "el buzón de voz", "语音信箱。例：Tenía el buzón de voz lleno y no entraban más mensajes."],
      ["Sustantivo", "el canal privado", "私人频道。例：El programa se emite en un canal privado."],
      ["Sustantivo", "el canal público", "公共频道。例：Lo vi anoche en un canal público."],
      ["Sustantivo", "la telebasura", "低俗电视节目。例：No soporto la telebasura de por la tarde."],
      ["Sustantivo", "periodista", "记者。例：La periodista hizo una pregunta bastante incómoda."],
    ]),
  },
  {
    slug: "medio-ambiente-sociedad",
    number: "09",
    title: "Medio ambiente y sociedad",
    subtitle: "环境与社会议题，偏 B1+ 观点型词汇",
    accent: "#3f8b74",
    points: [
      "适合 DELE 很爱出的社会与环保话题。",
      "不只会 reciclar，而是能说行动和影响。",
      "词汇偏观点型和公共讨论型。",
      "非常适合写作和口语讨论。",
    ],
    why: "这一组是 B1 很容易卡住的部分，因为很多词平时看得少、但考试爱考。",
    core: [
      "优先记措施、问题和参与类表达。",
      "例句尽量想成观点句。",
      "很多词能直接拿去作文。",
    ],
    focus: [
      "先记环保行动。",
      "再记社会问题。",
      "最后补参与和改变。",
    ],
    cards: makeCards([
      ["Expresión", "reducir emisiones", "减少排放。例：La ciudad quiere reducir emisiones con nuevas medidas."],
      ["Sustantivo", "el desperdicio alimentario", "食物浪费。例：Cada vez se habla más del desperdicio alimentario."],
      ["Sustantivo", "la concienciación", "意识提升。例：Hace falta más concienciación desde la escuela."],
      ["Sustantivo", "la medida sostenible", "可持续措施。例：No todas las medidas sostenibles son fáciles de aplicar."],
      ["Sustantivo", "el compromiso ciudadano", "公民责任感。例：Sin compromiso ciudadano, el cambio es muy lento."],
      ["Sustantivo", "el voluntariado", "志愿服务。例：Participó en un voluntariado durante todo el verano."],
      ["Verbo", "visibilizar", "让…被看见。例：La campaña busca visibilizar un problema bastante ignorado."],
      ["Sustantivo", "la desigualdad social", "社会不平等。例：La desigualdad social sigue marcando muchas oportunidades."],
      ["Expresión", "el acceso limitado", "受限获取。例：En algunas zonas el acceso a la sanidad es limitado."],
      ["Sustantivo", "el desarrollo sostenible", "可持续发展。例：Hablar de desarrollo sostenible ya no es opcional."],
      ["Sustantivo", "la movilidad urbana", "城市出行。例：La movilidad urbana debería pensarse mejor."],
      ["Expresión", "reutilizar recursos", "重复利用资源。例：La idea es reutilizar recursos antes de comprar más."],
      ["Sustantivo", "la sequía prolongada", "长期干旱。例：La sequía prolongada afecta a toda la región."],
      ["Sustantivo", "la contaminación acústica", "噪音污染。例：La contaminación acústica también perjudica la salud."],
      ["Sustantivo", "la iniciativa vecinal", "居民倡议。例：Todo empezó con una pequeña iniciativa vecinal."],
      ["Sustantivo", "la recogida selectiva", "分类回收。例：En mi barrio aún falta mejorar la recogida selectiva."],
      ["Expresión", "reclamar mejoras", "要求改善。例：Los vecinos llevan meses reclamando mejoras."],
      ["Verbo", "sensibilizar", "提高意识。例：El documental pretende sensibilizar a los más jóvenes."],
      ["Sustantivo", "el consumo energético", "能源消耗。例：Queremos reducir el consumo energético de casa."],
      ["Sustantivo", "la exclusión social", "社会排斥。例：La exclusión social no se resuelve solo con buenas intenciones."],
      ["Sustantivo", "la ayuda mutua", "互助。例：En momentos difíciles la ayuda mutua se vuelve esencial."],
      ["Sustantivo", "la precariedad", "不稳定；拮据状态。例：La precariedad afecta sobre todo a los jóvenes."],
      ["Sustantivo", "el impacto ambiental", "环境影响。例：Antes de construirlo deberían estudiar el impacto ambiental."],
      ["Verbo", "implicarse", "投入参与。例：Si la gente no se implica, nada cambia."],
      ["Expresión", "impulsar cambios", "推动改变。例：A veces una sola idea puede impulsar cambios reales."],
      ["Sustantivo", "la emergencia climática", "气候紧急状态。例：Muchos expertos hablan ya de emergencia climática."],
      ["Sustantivo", "la escasez de recursos", "资源匮乏。例：La escasez de recursos obliga a replantearlo todo."],
      ["Expresión", "hacer un uso responsable", "负责任使用。例：Deberíamos hacer un uso responsable del agua."],
      ["Sustantivo", "la participación ciudadana", "公民参与。例：Sin participación ciudadana las medidas se quedan cortas."],
      ["Sustantivo", "la red de apoyo", "支持网络。例：Las redes de apoyo son esenciales en barrios vulnerables."],
      ["Expresión", "poner el foco en", "聚焦。例：La campaña pone el foco en los colectivos más olvidados."],
      ["Verbo", "denunciar", "揭露；控诉。例：Varias asociaciones denunciaron la situación públicamente."],
      ["Sustantivo", "la medida insuficiente", "不充分措施。例：Muchos consideran que es una medida insuficiente."],
      ["Sustantivo", "la vulnerabilidad", "脆弱处境。例：La crisis aumentó la vulnerabilidad de muchas familias."],
      ["Sustantivo", "el impacto social", "社会影响。例：No basta con mirar el coste; también hay que mirar el impacto social."],
      ["Expresión", "promover hábitos sostenibles", "推动可持续习惯。例：La escuela quiere promover hábitos sostenibles desde pequeños."],
      ["Sustantivo", "la recogida de firmas", "征集签名。例：Organizaron una recogida de firmas en pocos días."],
      ["Expresión", "mejorar la convivencia", "改善共处。例：Hay propuestas sencillas para mejorar la convivencia del barrio."],
      ["Sustantivo", "la respuesta colectiva", "集体回应。例：Sin respuesta colectiva el problema seguirá creciendo."],
      ["Verbo", "movilizarse", "动员起来。例：Los vecinos se movilizaron para evitar el cierre."],
      ["Expresión", "reducir la huella", "减少足迹。例：Estamos intentando reducir nuestra huella ambiental."],
      ["Sustantivo", "la falta de oportunidades", "机会缺乏。例：La falta de oportunidades empuja a muchos a irse."],
      ["Sustantivo", "el contenedor de reciclaje", "回收箱。例：En mi calle por fin pusieron un contenedor de reciclaje nuevo."],
      ["Sustantivo", "el cambio climático", "气候变化。例：El cambio climático ya afecta a las cosechas de la zona."],
      ["Sustantivo", "la energía solar", "太阳能。例：Cada vez más edificios apuestan por la energía solar."],
      ["Sustantivo", "las energías alternativas", "替代能源。例：Las energías alternativas ganan importancia año tras año."],
      ["Sustantivo", "la capa de ozono", "臭氧层。例：En clase hablaron de la importancia de proteger la capa de ozono."],
      ["Sustantivo", "el agujero de la capa de ozono", "臭氧层空洞。例：Antes se hablaba mucho del agujero de la capa de ozono."],
      ["Sustantivo", "la energía eólica", "风能。例：El país ha invertido bastante en energía eólica."],
    ]),
  },
  {
    slug: "cultura-ocio",
    number: "10",
    title: "Cultura y ocio",
    subtitle: "文化娱乐从基础兴趣升级到评价表达",
    accent: "#9b6b4b",
    points: [
      "不是简单说喜欢电影，而是能评价内容和形式。",
      "特别适合口语推荐和评论。",
      "也适合写短评、谈活动体验。",
      "词汇偏 B1+ 审美和感受表达。",
    ],
    why: "文化题很常见，但很多人只会说 me gusta。你需要的是更像评价的词。",
    core: [
      "优先记评价作品的表达。",
      "很多词适合推荐电影、展览和书。",
      "注意名词和形容词搭配。",
    ],
    focus: [
      "先记作品结构。",
      "再记观看感受。",
      "最后补活动和展览。",
    ],
    cards: makeCards([
      ["Sustantivo", "la puesta en escena", "舞台呈现；呈现场面。例：La puesta en escena me pareció elegantísima."],
      ["Sustantivo", "la trama", "情节。例：La trama es lenta al principio, pero luego mejora mucho."],
      ["Sustantivo", "el desenlace", "结局。例：No me convenció nada el desenlace de la película."],
      ["Sustantivo", "el ritmo narrativo", "叙事节奏。例：El ritmo narrativo se me hizo irregular."],
      ["Expresión", "estar sobrevalorado/a", "被高估。例：A mí esa serie me parece un poco sobrevalorada."],
      ["Expresión", "recomendar encarecidamente", "强烈推荐。例：Te la recomiendo encarecidamente si te gusta el suspense."],
      ["Verbo", "transmitir", "传达。例：La novela transmite muy bien la tensión del momento."],
      ["Verbo", "emocionar", "打动。例：Me emocionó más de lo que esperaba."],
      ["Sustantivo", "el enfoque", "切入角度。例：El enfoque del documental es original y muy humano."],
      ["Sustantivo", "la interpretación", "表演。例：La interpretación principal sostiene toda la obra."],
      ["Sustantivo", "el estreno", "首映；新上映。例：Quiero ir al estreno si consigo entradas."],
      ["Sustantivo", "la exposición temporal", "临时展览。例：Fuimos a una exposición temporal sobre diseño contemporáneo."],
      ["Verbo", "asistir a", "参加；出席。例：Asistimos a una charla bastante interesante."],
      ["Expresión", "disfrutar al máximo", "尽情享受。例：Quiero disfrutar al máximo de esos días libres."],
      ["Sustantivo", "el punto de vista artístico", "艺术视角。例：Me interesa mucho su punto de vista artístico."],
      ["Sustantivo", "la reseña", "评论。例：Leí una reseña muy buena y por eso fui."],
      ["Expresión", "captar la atención", "吸引注意。例：El principio capta la atención enseguida."],
      ["Sustantivo", "el ambiente", "氛围。例：El ambiente del festival era muy relajado."],
      ["Sustantivo", "la propuesta cultural", "文化活动提案。例：Me encanta que haya tanta propuesta cultural en otoño."],
      ["Sustantivo", "la producción", "制作。例：Se nota que es una producción muy cuidada."],
      ["Sustantivo", "el repertorio", "曲目；保留节目。例：El repertorio mezclaba temas clásicos y modernos."],
      ["Sustantivo", "el montaje", "剪辑；舞台编排。例：El montaje me pareció demasiado largo."],
      ["Sustantivo", "el público", "观众。例：El público reaccionó con muchísimo entusiasmo."],
      ["Sustantivo", "la experiencia inmersiva", "沉浸式体验。例：Fue una experiencia inmersiva y bastante distinta."],
      ["Sustantivo", "el valor cultural", "文化价值。例：Ese edificio tiene un valor cultural enorme."],
      ["Expresión", "estar bien planteado/a", "构思得好。例：La idea está bien planteada, aunque el final flojea."],
      ["Sustantivo", "la ambientación", "氛围营造。例：La ambientación de la película está muy lograda."],
      ["Sustantivo", "el hilo conductor", "主线。例：El hilo conductor se pierde un poco en la segunda mitad."],
      ["Expresión", "dejar huella", "留下印象。例：Es una novela que deja huella durante días."],
      ["Verbo", "enganchar", "抓住人。例：A mí no me enganchó hasta el tercer capítulo."],
      ["Adjetivo", "pretencioso/a", "故作高深的。例：Visualmente me gustó, pero a ratos me pareció pretenciosa."],
      ["Adjetivo", "sobrio/a", "克制简洁的。例：La puesta en escena es sobria y muy efectiva."],
      ["Sustantivo", "el ritmo pausado", "缓慢节奏。例：Si no te gusta el ritmo pausado, quizás no sea para ti."],
      ["Expresión", "estar a la altura de", "配得上。例：La segunda temporada no estuvo a la altura de la primera."],
      ["Sustantivo", "la propuesta arriesgada", "大胆尝试。例：Me gustan las propuestas arriesgadas aunque no siempre funcionen."],
      ["Verbo", "reinterpretar", "重新诠释。例：La directora reinterpreta un tema clásico desde otro ángulo."],
      ["Expresión", "transmitir una sensación", "传达一种感觉。例：La música transmite una sensación de inquietud constante."],
      ["Sustantivo", "la coherencia", "连贯性。例：Lo mejor del libro es su coherencia interna."],
      ["Sustantivo", "el exceso de metraje", "片长过长。例：Le sobra media hora de metraje, en mi opinión."],
      ["Expresión", "salir con ganas de pensar", "看完后想继续思考。例：Salí del cine con ganas de pensar un rato."],
      ["Sustantivo", "la lectura superficial", "浅层解读。例：La obra permite algo más que una lectura superficial."],
      ["Expresión", "ganar fuerza", "变得更有力量。例：La historia gana fuerza a medida que avanza."],
      ["Sustantivo", "la cartelera", "电影排片；活动看板。例：Miramos la cartelera antes de decidir qué ver."],
      ["Expresión", "sacar las entradas", "取票；买票。例：Ve sacando las entradas mientras yo busco la sala."],
      ["Sustantivo", "la sesión", "场次。例：La sesión de las ocho estaba casi llena."],
      ["Sustantivo", "espectador/a", "观众。例：Los espectadores aplaudieron al final de la función."],
      ["Sustantivo", "el polideportivo", "综合体育馆。例：Los partidos del barrio se juegan en el polideportivo."],
      ["Expresión", "pasarlo mal/fatal", "玩得不开心；过得糟。例：Lo pasó fatal porque no conocía a nadie."],
      ["Sustantivo", "la butaca", "剧院座位。例：Nos tocaron unas butacas bastante cómodas."],
      ["Sustantivo", "la función", "演出；场次。例：La función empezó con diez minutos de retraso."],
      ["Sustantivo", "el pase", "招待券；入场证。例：Le dieron un pase para entrar sin hacer cola."],
      ["Sustantivo", "la taquilla", "售票处。例：Todavía quedaban entradas en la taquilla."],
      ["Expresión", "ser aficionado/a a", "爱好……。例：Es muy aficionado al tenis desde pequeño."],
      ["Sustantivo", "bailarín/a", "舞者。例：La bailarina principal estuvo magnífica."],
      ["Sustantivo", "novelista", "小说家。例：Esa novelista sabe crear personajes muy vivos."],
      ["Sustantivo", "solista", "独奏者；独唱者。例：El solista salió al escenario al final del concierto."],
      ["Expresión", "pasarlo bomba", "玩得特别开心。例：En el concierto lo pasamos bomba."],
      ["Expresión", "aburrirse como una ostra", "无聊透顶。例：Si voy solo a ese tipo de actos, me aburro como una ostra."],
      ["Sustantivo", "jugador/a", "参赛者；球员。例：Uno de los jugadores se lesionó en la segunda parte."],
      ["Sustantivo", "árbitro/a", "裁判。例：El árbitro anuló el gol por fuera de juego."],
    ]),
  },
  {
    slug: "comida-restaurante",
    number: "11",
    title: "Comida y restaurante",
    subtitle: "饮食与餐馆，从基础点餐升级到评价口味",
    accent: "#c07b3d",
    points: [
      "不止会 pedir la cuenta，而是能评价食物和习惯。",
      "适合旅行、聚餐、口语和写作。",
      "高频搭配很多。",
      "比基础饮食词更偏 B1+。",
    ],
    why: "饮食话题非常常见，但真正好用的是味道、习惯和体验类表达。",
    core: [
      "优先记口味、做法和饮食习惯。",
      "很多表达特别适合点评一家店。",
      "例句可直接改成自己的饮食经验。",
    ],
    focus: [
      "先记口味评价。",
      "再记饮食习惯。",
      "最后补餐厅体验。",
    ],
    cards: makeCards([
      ["Sustantivo", "el plato contundente", "分量足的菜。例：Era un plato contundente y casi no pude acabarlo."],
      ["Sustantivo", "la comida procesada", "加工食品。例：Intento reducir la comida procesada durante la semana."],
      ["Sustantivo", "el hábito alimentario", "饮食习惯。例：Cambiar los hábitos alimentarios lleva tiempo."],
      ["Expresión", "moderar el azúcar", "控制糖分。例：Quiero moderar el azúcar sin volverme obsesiva."],
      ["Expresión", "el sabor intenso", "味道浓。例：Tiene un sabor intenso, pero bastante equilibrado."],
      ["Sustantivo", "la textura", "口感；质地。例：La textura era rara, aunque el sabor estaba bien."],
      ["Sustantivo", "el punto de cocción", "火候。例：El pescado estaba en su punto de cocción."],
      ["Sustantivo", "el producto de temporada", "时令产品。例：Prefieren cocinar con productos de temporada."],
      ["Expresión", "el menú equilibrado", "均衡菜单。例：En casa intentamos seguir un menú equilibrado."],
      ["Sustantivo", "la intolerancia", "不耐受。例：Desde que descubrió la intolerancia, come de otra manera."],
      ["Sustantivo", "la digestión pesada", "消化负担重。例：Cenar tan tarde siempre me deja una digestión pesada."],
      ["Expresión", "picar entre horas", "两餐间吃零食。例：Estoy intentando dejar de picar entre horas."],
      ["Expresión", "darse un atracón", "暴吃。例：El fin de semana pasado me di un atracón de dulce."],
      ["Sustantivo", "el ingrediente principal", "主要食材。例：El ingrediente principal cambia según la temporada."],
      ["Verbo", "sazonar", "调味。例：Sazona la ensalada al final para que quede mejor."],
      ["Expresión", "quedar seco/a", "做得太干。例：Si te pasas de tiempo, el arroz queda seco."],
      ["Expresión", "estar en su punto", "火候刚好。例：La carne estaba en su punto y muy tierna."],
      ["Sustantivo", "la presentación del plato", "摆盘。例：La presentación del plato era sencilla pero cuidada."],
      ["Expresión", "reservar con antelación", "提前预订。例：Conviene reservar con antelación los fines de semana."],
      ["Expresión", "el servicio atento", "服务周到。例：Además de la comida, destacaría el servicio atento."],
      ["Sustantivo", "la relación calidad-precio", "性价比。例：La relación calidad-precio me pareció excelente."],
      ["Expresión", "evitar excesos", "避免过量。例：Entre semana intento evitar excesos."],
      ["Expresión", "cocinar a fuego lento", "慢火炖煮。例：Mi abuelo cocinaba ese guiso a fuego lento."],
      ["Expresión", "probar sabores nuevos", "尝试新口味。例：Cuando viajo me gusta probar sabores nuevos."],
      ["Expresión", "seguir una alimentación variada", "保持多样饮食。例：No siempre es fácil seguir una alimentación variada."],
      ["Sustantivo", "el sabor ahumado", "烟熏味。例：La salsa tenía un sabor ahumado muy interesante."],
      ["Sustantivo", "el toque especiado", "香料感。例：Le daría un toque especiado un poco más suave."],
      ["Expresión", "quedar poco hecho", "煎得偏生。例：A mí la carne me gusta poco hecha, pero esta quedó demasiado cruda."],
      ["Expresión", "resultar empalagoso/a", "甜得发腻。例：El postre estaba bueno, aunque a ratos resultaba empalagoso."],
      ["Sustantivo", "la comida copiosa", "丰盛的一餐。例：No me sientan bien las comidas demasiado copiosas."],
      ["Expresión", "sentar pesado", "吃了觉得沉。例：La cena me sentó pesada porque era muy tarde."],
      ["Sustantivo", "el antojo", "嘴馋；突然想吃。例：De vez en cuando me da antojo de algo dulce."],
      ["Expresión", "respetar una dieta", "遵守饮食要求。例：En casa intentamos respetar una dieta bastante equilibrada."],
      ["Sustantivo", "la ración escasa", "分量少。例：La ración me pareció escasa para el precio."],
      ["Sustantivo", "la materia prima", "原材料。例：Se nota cuando un sitio cuida la materia prima."],
      ["Sustantivo", "el producto fresco", "新鲜食材。例：Prefiero comprar producto fresco aunque dure menos."],
      ["Expresión", "tener buen paladar", "味觉好。例：Mi hermana tiene muy buen paladar para detectar sabores."],
      ["Verbo", "maridar", "搭配酒菜。例：Nos recomendaron cómo maridar cada plato."],
      ["Expresión", "quedar jugoso/a", "保持多汁。例：Si lo cocinas así, queda mucho más jugoso."],
      ["Sustantivo", "la cocina de aprovechamiento", "不浪费食材的做法。例：Últimamente me interesa la cocina de aprovechamiento."],
      ["Expresión", "tener demasiada grasa", "油脂过多。例：Para mi gusto tenía demasiada grasa."],
      ["Expresión", "comer con moderación", "适量饮食。例：No se trata de prohibirse nada, sino de comer con moderación."],
    ]),
  },
  {
    slug: "opinion-comunicacion",
    number: "12",
    title: "Opinión y comunicación",
    subtitle: "观点表达升级版，偏 B1+ 讨论与论证",
    accent: "#6c6fa9",
    points: [
      "不是简单表达喜欢不喜欢，而是能组织观点。",
      "特别适合口语讨论、写作和复述。",
      "很多词都属于 B1 往上非常实用的骨架词。",
      "这一组最值得反复刷。",
    ],
    why: "如果你语法已经够了，真正决定表达质量的就是这一组组织观点的词。",
    core: [
      "优先记解释、让步、反驳和澄清。",
      "很多表达都能直接提升写作层次。",
      "例句尽量想成讨论题场景。",
    ],
    focus: [
      "先记论证和解释。",
      "再记讨论与协商。",
      "最后补更细的反驳和修正表达。",
    ],
    cards: makeCards([
      ["Verbo", "matizar", "补充说明；细化。例：No estoy en desacuerdo, pero me gustaría matizar una cosa."],
      ["Expresión", "argumentar con claridad", "清楚论证。例：Le cuesta argumentar con claridad cuando se pone nervioso."],
      ["Verbo", "malinterpretar", "误解。例：Creo que malinterpretaste lo que intentaba decir."],
      ["Expresión", "aclarar un malentendido", "澄清误会。例：Nos sentamos a hablar para aclarar el malentendido."],
      ["Expresión", "sostener una idea", "坚持一个观点。例：No pudo sostener su idea con ejemplos concretos."],
      ["Expresión", "llegar a la conclusión", "得出结论。例：Después de comparar datos, llegaron a la conclusión de que no compensaba."],
      ["Expresión", "plantear una objeción", "提出异议。例：Nadie planteó una objeción realmente sólida."],
      ["Verbo", "reformular", "换种方式表达。例：¿Puedes reformular la pregunta de una manera más simple?"],
      ["Expresión", "hacer una propuesta viable", "提出可行方案。例：Lo difícil no es criticar, sino hacer una propuesta viable."],
      ["Expresión", "defender un punto de vista", "捍卫观点。例：Supó defender su punto de vista sin levantar la voz."],
      ["Verbo", "interrumpir", "打断。例：No me gusta que me interrumpan cuando estoy explicando algo."],
      ["Expresión", "ceder la palabra", "让出发言权。例：Voy a cederle la palabra a Marta para que continúe."],
      ["Expresión", "resumir lo esencial", "概括要点。例：Al final de la presentación resumió lo esencial en dos minutos."],
      ["Expresión", "sacar una conclusión", "得出结论。例：Todavía es pronto para sacar una conclusión definitiva."],
      ["Expresión", "poner un ejemplo", "举例。例：Si pones un ejemplo, se entiende mucho mejor."],
      ["Expresión", "justificar una postura", "为立场辩护。例：No logró justificar su postura de forma convincente."],
      ["Expresión", "tener criterio", "有判断力。例：Con el tiempo va teniendo más criterio para decidir."],
      ["Verbo", "discrepar", "持不同意见。例：Se puede discrepar sin faltar al respeto."],
      ["Expresión", "dar por válido", "视为成立。例：No podemos dar por válido ese dato sin comprobarlo."],
      ["Verbo", "rectificar", "改正；修正。例：Cuando vio el error, rectificó enseguida."],
      ["Verbo", "precisar", "明确说明。例：Tendrías que precisar mejor a qué periodo te refieres."],
      ["Verbo", "rebatir", "反驳。例：No fue capaz de rebatir los argumentos contrarios."],
      ["Expresión", "quedar claro", "变清楚。例：Después del debate quedaron claras varias diferencias."],
      ["Expresión", "convencer con argumentos", "用论据说服。例：No basta con opinar: hay que convencer con argumentos."],
      ["Expresión", "dejar constancia de", "明确记录。例：Quisieron dejar constancia de su desacuerdo por escrito."],
      ["Expresión", "dar a entender", "暗示。例：No dijo eso directamente, pero lo dio a entender."],
      ["Verbo", "cuestionar", "质疑。例：Muchos empezaron a cuestionar esa decisión."],
      ["Expresión", "desviar el tema", "把话题带偏。例：Cada vez que se complica, desvía el tema."],
      ["Expresión", "centrarse en lo esencial", "聚焦核心。例：Para explicarlo bien, conviene centrarse en lo esencial."],
      ["Sustantivo", "la contradicción", "矛盾。例：Hay una contradicción clara entre lo que dice y lo que hace."],
      ["Expresión", "matizar una postura", "细化立场。例：Quiso matizar su postura para que no sonara tan tajante."],
      ["Sustantivo", "el intercambio de ideas", "思想交流。例：Lo mejor de la clase fue el intercambio de ideas."],
      ["Expresión", "sacar el tema", "提起话题。例：Nadie quiso sacar el tema durante la cena."],
      ["Verbo", "malinterpretar", "误解。例：No quiero que se malinterprete lo que estoy diciendo."],
      ["Expresión", "afinar un argumento", "打磨论点。例：Todavía tienes tiempo para afinar tu argumento principal."],
      ["Sustantivo", "la objeción razonable", "合理异议。例：Planteó una objeción razonable y nadie supo responder."],
      ["Expresión", "hacer una precisión", "补充说明。例：Antes de seguir, quiero hacer una precisión importante."],
      ["Expresión", "mantener una postura", "维持立场。例：Aun así, mantuvo su postura hasta el final."],
      ["Expresión", "resolver una duda", "解决疑问。例：La última diapositiva me ayudó a resolver varias dudas."],
      ["Sustantivo", "la formulación", "措辞；表述。例：La idea era buena, pero la formulación no tanto."],
      ["Verbo", "contradecir", "反驳；与…矛盾。例：Los datos contradicen esa interpretación tan simple."],
      ["Expresión", "llegar al fondo del asunto", "弄清问题本质。例：Si no hablamos claro, no llegaremos al fondo del asunto."],
    ]),
  },
];

const STUDY_DATA = {
  title: "Español DELE B1+ Vocab",
  storageKey: "spanish-dele-b1-plus-vocab-progress",
  chapters: TOPICS.map((topic) => ({
    ...topic,
    pages: "B1+",
    level: "DELE B1+",
  })),
};
